import { blocks, nestable, option } from "@jimdrury/storyblok-component-schema";

export default nestable({
  name: "grid_item",
  display_name: "Grid Item",
  folder: "layout",
  schema: [
    blocks({
      name: "body",
      allowed_folders: ["layout", "components"],
      required: true,
      minimum: 1,
    }),
    option({
      name: "col_span_mobile",
      description: "Column span on mobile (1-12).",
      default_value: "12",
      options: [
        { name: "1", value: "1" },
        { name: "2", value: "2" },
        { name: "3", value: "3" },
        { name: "4", value: "4" },
        { name: "5", value: "5" },
        { name: "6", value: "6" },
        { name: "7", value: "7" },
        { name: "8", value: "8" },
        { name: "9", value: "9" },
        { name: "10", value: "10" },
        { name: "11", value: "11" },
        { name: "12", value: "12" },
      ],
    }),
    option({
      name: "col_span_tablet",
      description: "Column span on tablet (md breakpoint, 1-12).",
      default_value: "6",
      options: [
        { name: "1", value: "1" },
        { name: "2", value: "2" },
        { name: "3", value: "3" },
        { name: "4", value: "4" },
        { name: "5", value: "5" },
        { name: "6", value: "6" },
        { name: "7", value: "7" },
        { name: "8", value: "8" },
        { name: "9", value: "9" },
        { name: "10", value: "10" },
        { name: "11", value: "11" },
        { name: "12", value: "12" },
      ],
    }),
    option({
      name: "col_span_desktop",
      description: "Column span on desktop (lg breakpoint, 1-12).",
      default_value: "4",
      options: [
        { name: "1", value: "1" },
        { name: "2", value: "2" },
        { name: "3", value: "3" },
        { name: "4", value: "4" },
        { name: "5", value: "5" },
        { name: "6", value: "6" },
        { name: "7", value: "7" },
        { name: "8", value: "8" },
        { name: "9", value: "9" },
        { name: "10", value: "10" },
        { name: "11", value: "11" },
        { name: "12", value: "12" },
      ],
    }),
  ],
});
